### ISSUE TITLE
how to not save space

### ISSUE THREAD

**Issue by crashbtz** [kanakiyajay/bootstrap-grid-builder#1]
Hello,
Firstable I'm french so sorry for my english.
this grid builder is very closed about I'm looking for. The only thing is it seems to try to save space.
In your demo, is it possible to put 3 small span4 on 3 differents lines? 
For example:
the first one on the left, the second on the right and the last one on the middle (or everywhere on the line) ?

Thank you for your help

**Comment by kanakiyajay** [comment]
Its an issue .Currently because of time constraints i am not working on bootstrap-grid-builder.

I will advise you to visit http://jaykanakiya.com/bootstrap-grid-builder-v1/

It has got a simpler interface.You can first add rows and then add cols
