### ISSUE TITLE
License

### ISSUE THREAD

**Issue by dovy** [kanakiyajay/bootstrap-grid-builder#2]
Love what you do, wish you'd go GPL instead of Apache. I have no interest in doing something with Boostrap, but I love the grid concept. Any chance I could use it in a different vertical?

**Comment by kanakiyajay** [comment]
Whats the problem in Apache, can you expand your opinion ?

**Comment by dovy** [comment]
Want to make a WordPress plugin and sell it.  (NOT boodstrap building).

Being forced to give back all the code would kind of defeat the purpose.

**Comment by kanakiyajay** [comment]
You can even write your custom code, the grid concept will be easy to replicate, I think there are many wordpress plugins that have drag and drop layout building example http://www.layerswp.com

**Comment by dovy** [comment]
Yes, but you did a great job. I was just hoping to have a solid starting place. I am not quite strong with Angular yet.

**Comment by bdaug001** [comment]
I think you might be confused about Apache and GPL. The GPL license is the one that requires distribution of the source. Of the two licenses, Apache is the one thats less restrictive. There is nothing that prevents Apache code from being incorporated into a Wordpress plugin
